# Generated by Django 3.2.9 on 2021-11-13 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsable', models.IntegerField()),
                ('userAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='commonUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=30)),
                ('userLastName', models.CharField(max_length=30)),
                ('userPhoneNumber', models.CharField(max_length=20)),
                ('userRut', models.CharField(max_length=20, unique=True)),
                ('userType', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Profesional'), (2, 'Admin')], default=1)),
                ('disabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAuth.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
