# Generated by Django 3.2.8 on 2021-10-25 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRut', models.CharField(max_length=20)),
                ('userType', models.IntegerField(choices=[(0, 'Administrador'), (1, 'Cliente'), (2, 'Profesional')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MainCliente',
        ),
    ]
