# Generated by Django 3.2.9 on 2021-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0003_remove_company_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('professionalAssigned', models.IntegerField()),
                ('client1', models.IntegerField()),
                ('client2', models.IntegerField()),
                ('client3', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
