# Generated by Django 3.2.9 on 2021-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0004_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Especial')], default=1)),
                ('nextPayment', models.DateField()),
                ('amount', models.IntegerField()),
                ('employeeID', models.IntegerField()),
                ('dateVisit', models.DateField()),
                ('description', models.TextField()),
                ('improvement', models.TextField()),
            ],
        ),
    ]
