# Generated by Django 3.2.8 on 2021-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0004_alter_commonusermodel_userrut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonusermodel',
            name='userAddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='userAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='userFirstName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='userLastName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='userPhoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='userRut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
