# Generated by Django 3.2.9 on 2021-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='improvement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Especial')], default=0),
        ),
    ]
