# Generated by Django 3.2.8 on 2021-11-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0005_auto_20211102_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='userAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='userFirstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='userLastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='userPhoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
