# Generated by Django 3.2.9 on 2021-11-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0006_auto_20211125_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edited',
            field=models.IntegerField(default=0),
        ),
    ]
