# Generated by Django 3.2.8 on 2021-11-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0006_auto_20211102_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='userAge',
            field=models.IntegerField(),
        ),
    ]
