# Generated by Django 3.2.8 on 2021-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0007_alter_commonusermodel_userage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonusermodel',
            name='userIsFired',
            field=models.IntegerField(default=0),
        ),
    ]
