# Generated by Django 3.2.8 on 2021-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0008_commonusermodel_userisfired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='userType',
            field=models.IntegerField(choices=[(0, 'Cliente'), (1, 'Profesional')], default=1),
        ),
    ]
