# Generated by Django 4.0 on 2021-12-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0009_alter_checklist_answer1_alter_checklist_answer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
