# Generated by Django 3.2.9 on 2021-11-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0009_alter_commonusermodel_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsable', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='systemAuth.company'),
        ),
    ]
