# Generated by Django 3.2.9 on 2021-11-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0010_auto_20211111_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonusermodel',
            name='userAddress',
        ),
        migrations.RemoveField(
            model_name='commonusermodel',
            name='userAge',
        ),
        migrations.RemoveField(
            model_name='commonusermodel',
            name='userIsFired',
        ),
        migrations.AddField(
            model_name='commonusermodel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='userAddress',
            field=models.CharField(default='caca', max_length=50),
        ),
        migrations.AlterField(
            model_name='commonusermodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAuth.company'),
        ),
    ]
