# Generated by Django 4.0 on 2021-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAuth', '0010_alter_commonusermodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='company',
            field=models.IntegerField(),
        ),
    ]
